name 'filebeat'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures filebeat'
long_description 'Installs/Configures filebeat'
version '0.1.0'
