name 'logstash'
maintainer 'Ed Babrounik'
maintainer_email 'eduard.babrounik@minsk.finfactory.com'
license 'all_rights'
description 'Installs/Configures logstash'
long_description 'Installs/Configures latest logstash from its yum repo.'
version '0.1.0'
