name 'marvel'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures marvel'
long_description 'Installs/Configures marvel'
depends 'elasticsearch'
depends 'kibana'
version '0.1.0'
