name 'kibana'
maintainer 'Ed Babrounik'
maintainer_email 'eduard.babrounik@minsk.finfactory.com'
license 'all_rights'
description 'Installs/Configures kibana'
long_description 'Installs/Configures latest version of kibana from its yum repo.'
version '0.1.0'
