---
driver:
  name: vagrant

provisioner:
  name: shell 

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["private_network", {ip: "192.168.19.90"}]
      customize:
        memory: 1000

suites:
  - name: node-dv0 
    run_list:
    attributes:
